# from game_exceptions import IncorrectUserAttackInput
#
# try:
#     print(int(input()))
# except ValueError:
#     print('got ValueError')
# raise IncorrectUserAttackInput
a = {1: "a",
     2: "b"}
print(a[3])
KeyError
